#!/usr/bin/env bash
# Interactive, idempotent VPS installer for VultMirror.
set -Eeuo pipefail

PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$PROJECT_DIR/.venv"
ENV_FILE="$PROJECT_DIR/.env"
PYTHON_BIN="${PYTHON_BIN:-python3}"
INSTALL_SERVICE=true
INSTALL_DEPS=true

usage() {
    cat <<'EOF'
Usage: ./setup.sh [--no-service] [--skip-deps]

Sets up VultMirror in a virtual environment, securely writes .env after
prompting for Telegram credentials, and optionally installs a systemd service.

Environment variables BOT_TOKEN and ADMIN_USER_ID support non-interactive automation.
Set PYTHON_BIN to override python3.
EOF
}

for argument in "$@"; do
    case "$argument" in
        --no-service) INSTALL_SERVICE=false ;;
        --skip-deps) INSTALL_DEPS=false ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown option: $argument" >&2; usage >&2; exit 2 ;;
    esac
done

die() { echo "Error: $*" >&2; exit 1; }

prompt() {
    local label="$1" current="$2" secret="${3:-false}" value=""
    if [[ -n "$current" ]]; then
        if [[ "$secret" == true ]]; then
            printf '%s already exists. Press Enter to keep it, or enter a replacement: ' "$label" >&2
        else
            printf '%s [%s]: ' "$label" "$current" >&2
        fi
    else
        printf '%s: ' "$label" >&2
    fi
    if [[ "$secret" == true ]]; then
        IFS= read -r -s value < /dev/tty || die "Unable to read $label from the terminal."
        printf '\n' >&2
    else
        IFS= read -r value < /dev/tty || die "Unable to read $label from the terminal."
    fi
    printf '%s' "${value:-$current}"
}

read_env_value() {
    local key="$1"
    [[ -f "$ENV_FILE" ]] || return 0
    sed -n "s/^${key}=//p" "$ENV_FILE" | tail -n 1
}

command -v "$PYTHON_BIN" >/dev/null 2>&1 || die "Python 3.10 or later is required. Install it, then rerun this script."
PYTHON_VERSION="$($PYTHON_BIN -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
if ! "$PYTHON_BIN" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)'; then
    die "Python 3.10 or later is required (found $PYTHON_VERSION)."
fi

echo "==> VultMirror setup in $PROJECT_DIR"
existing_token="${BOT_TOKEN:-$(read_env_value BOT_TOKEN)}"
existing_admin_id="${ADMIN_USER_ID:-$(read_env_value ADMIN_USER_ID)}"
existing_db_path="${DB_PATH:-$(read_env_value DB_PATH)}"

if [[ -t 0 || -t 1 ]]; then
    BOT_TOKEN="$(prompt 'Telegram bot token' "$existing_token" true)"
    ADMIN_USER_ID="$(prompt 'Telegram admin user ID' "$existing_admin_id")"
else
    BOT_TOKEN="$existing_token"
    ADMIN_USER_ID="$existing_admin_id"
fi

[[ "$BOT_TOKEN" =~ ^[0-9]+:[A-Za-z0-9_-]+$ ]] || die "BOT_TOKEN does not look like a Telegram bot token."
[[ "$ADMIN_USER_ID" =~ ^[0-9]+$ && "$ADMIN_USER_ID" != 0 ]] || die "ADMIN_USER_ID must be a non-zero numeric Telegram user ID."

umask 077
tmp_env="$(mktemp "$PROJECT_DIR/.env.XXXXXX")"
trap 'rm -f "$tmp_env"' EXIT
printf '# Generated by setup.sh — keep this file private.\nBOT_TOKEN=%s\nADMIN_USER_ID=%s\n' "$BOT_TOKEN" "$ADMIN_USER_ID" > "$tmp_env"
if [[ -n "$existing_db_path" ]]; then
    printf 'DB_PATH=%s\n' "$existing_db_path" >> "$tmp_env"
fi
mv "$tmp_env" "$ENV_FILE"
chmod 600 "$ENV_FILE"
trap - EXIT

if [[ "$INSTALL_DEPS" == true ]]; then
    echo "==> Creating Python virtual environment"
    "$PYTHON_BIN" -m venv "$VENV_DIR"
    echo "==> Installing dependencies"
    "$VENV_DIR/bin/python" -m pip install -r "$PROJECT_DIR/requirements.txt"
fi

[[ -x "$VENV_DIR/bin/python" ]] || die "Virtual environment is missing. Rerun without --skip-deps."
echo "==> Initializing database"
(cd "$PROJECT_DIR" && "$VENV_DIR/bin/python" -c 'from database import Database; Database()')

if [[ "$INSTALL_SERVICE" == true ]]; then
    printf 'Install and start a systemd service so the bot restarts after reboots? [Y/n]: ' >&2
    IFS= read -r service_answer < /dev/tty || service_answer="n"
    if [[ ! "$service_answer" =~ ^[Nn]$ ]]; then
        service_user="$(id -un)"
        service_file="/etc/systemd/system/vultmirror.service"
        echo "==> Installing systemd service as $service_user"
        sudo tee "$service_file" >/dev/null <<EOF
[Unit]
Description=VultMirror Telegram CA mirror bot
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$service_user
WorkingDirectory=$PROJECT_DIR
ExecStart=$VENV_DIR/bin/python $PROJECT_DIR/bot.py
Restart=on-failure
RestartSec=5
Environment=PYTHONUNBUFFERED=1

[Install]
WantedBy=multi-user.target
EOF
        sudo systemctl daemon-reload
        sudo systemctl enable --now vultmirror.service
        echo "==> Service is running. View logs with: sudo journalctl -u vultmirror -f"
    fi
fi

echo "==> Setup complete. Start manually with: $VENV_DIR/bin/python $PROJECT_DIR/bot.py"
